if: branch = master

language: node_js

node_js:
    - "14"

cache:
    directories:
        - node_modules

script:
    - npm run build -- --profile && cp CNAME build/CNAME

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
        branch: master
